# Generated by Django 6.0.1 on 2026-02-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
