# Generated by Django 6.0.1 on 2026-02-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_proof_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('final_solution', models.TextField()),
                ('verification_status', models.CharField(max_length=50)),
                ('total_attempts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sympy_code', models.TextField()),
                ('semantic_affirmation', models.TextField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='solver.engineeringproblem')),
            ],
        ),
    ]
