# Generated by Django 6.0.1 on 2026-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_engineeringproblem_verificationattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationattempt',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='verificationattempt',
            name='semantic_affirmation',
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='LLM_affirmation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='LLM_corrections',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='LLM_status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='code_error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='code_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='sympy_code',
            field=models.TextField(default=''),
        ),
    ]
