# Generated by Django 6.0.1 on 2026-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_remove_verificationattempt_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='full_LLM_output',
            field=models.TextField(default=''),
        ),
    ]
