# Generated by Django 6.0.1 on 2026-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0005_verificationattempt_full_llm_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='LLM_feedback',
            field=models.TextField(default=''),
        ),
    ]
