# Generated by Django 6.0.1 on 2026-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0006_verificationattempt_llm_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='is_sympy_error',
            field=models.BooleanField(default=False),
        ),
    ]
